local Color, colors, Group, groups, styles = require("colorbuddy").setup()

Color.new('foreground', '#c5cdd9')
Color.new('background', '#2B2D3A')
Color.new('background_red', '#ec7279')
Color.new('background_green', '#a0c980')
Color.new('background_blue', '#6cb6eb')
Color.new('background_purple', '#d38aea')

Color.new('diff_red', '#55393d')
Color.new('diff_green', '#394634')
Color.new('diff_blue', '#354157')
Color.new('diff_yellow', '#4e432f')

Color.new('black', '#202023')
Color.new('red', '#ec7279')
Color.new('yellow', '#deb974')
Color.new('green', '#a0c980')
Color.new('cyan', '#5dbbc1')
Color.new('blue', '#6cb6eb')
Color.new('purple', '#d38aea')
Color.new('grey', '#7e8294')
Color.new('grey_dim', '#5c6071')

Group.new('Normal', colors.foreground, colors.background, styles.NONE)
Group.new('Terminal', colors.foreground, colors.background, styles.NONE)
Group.new('EndOfBuffer', colors.background, colors.background, styles.NONE)
Group.new('Folded', colors.grey, colors.background, styles.NONE)
Group.new('FoldedColumn', colors.grey_dim, colors.background, styles.NONE)
Group.new('SignColumn', colors.foreground, colors.background, styles.NONE)
Group.new('IncSearch', colors.background, colors.background_blue, styles.NONE)
Group.new('Search', colors.background, colors.background_green, styles.NONE)
